minutes = int(input('Minutes ==> '))
print(minutes)
seconds = int(input('Seconds ==> '))
print(seconds)
miles = float(input('Miles ==> '))
print(miles)
pacem = int((minutes*60+seconds)/60//miles)
paces = int(((minutes*60+seconds)/60/miles-(minutes*60+seconds)/60//miles)*60)
speed = float(miles/((minutes*60+seconds)/(60*60)))
print()
print('Pace is',pacem,'minutes and',paces,'seconds per mile.')
print('Speed is',round(speed,2),'miles per hour.')