def encrypt(word):
    word=word.replace(' a','%4%')
    word=word.replace('he','7!')
    word=word.replace('e','9(*9(')
    word=word.replace('y','*%$')
    word=word.replace('u','@@@')
    word=word.replace('an','-?')
    word=word.replace('th','!@+3')
    word=word.replace('o','7654')
    word=word.replace('9','2')
    return word
def decrypt(word):
    word=word.replace('%4%',' a')
    word=word.replace('7!','he')
    word=word.replace('2','9')
    word=word.replace('9(*9(','e')
    word=word.replace('*%$','y')
    word=word.replace('@@@','u')
    word=word.replace('-?','an')
    word=word.replace('!@+3','th')
    word=word.replace('7654','o')
    return word
enter = input("Enter 'E' for encrypt or 'D' for decrypt ==> ")
print(enter)
if enter == 'e' or enter == 'E':
    a = input('Enter regular text ==> ')
    print(a)
    b = encrypt(a)
    print()
    print('Encrypted as ==>',b)
    n = len(b)-len(a)
    print('Difference in length ==>',n)
elif enter == 'd' or enter == 'D':
    a = input('Enter cipher text ==> ')
    print(a)
    b = decrypt(a)
    print()
    print('Deciphered as ==>',b)
    n = len(a)-len(b)
    print('Difference in length ==>',n)  
else:
    print('I didn\'t understand ... exiting')